Fix program logic
Fixes list:

Main: Return error if something happened.
Error: Clearer explanation.
Main: Set a child process that executes all the rest of childs.
Processes: No need to cleanup exec_args. Clearer message (pending to test for leaks)